name: 🐛 Отчёт об ошибке
description: Создайте отчёт, чтобы помочь нам стать лучше
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что нашли время сообщить об ошибке!
  - type: textarea
    id: bug-description
    attributes:
      label: Опишите ошибку
      description: Предоставьте чёткое и краткое описание того, в чём заключается ошибка.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Шаги для воспроизведения
      description: Опишите шаги, которые нужно выполнить, чтобы воспроизвести ошибку.
      placeholder: |
        1. Перейдите к '...'
        2. Нажмите на '....'
        3. Прокрутите до '....'
        4. Увидите ошибку
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Ожидаемое поведение
      description: Опишите, что должно было произойти по вашему мнению.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Информация о системе
        Пожалуйста, предоставьте информацию о системе, на которой вы столкнулись с ошибкой.
  - type: textarea
    id: desktop-info
    attributes:
      label: Компьютер (Desktop)
      description: Если ошибка произошла на компьютере, заполните эти поля.
      placeholder: |
        - ОС: [например, Windows 11, macOS]
        - Версия: [например, v1.2]
  - type: textarea
    id: additional-context
    attributes:
      label: Дополнительный контекст
      description: Добавьте любой другой контекст или скриншоты о проблеме здесь. Вы можете перетащить файлы прямо в это поле.