name: 💬 Другое
description: Для любых других вопросов или предложений
title: ""
labels: ["question"]
body:
  - type: textarea
    id: message
    attributes:
      label: Ваше сообщение
      description: Опишите ваш вопрос, предложение или любую другую тему.
    validations:
      required: true