name: C++/Qt Build and Test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            qt_arch: win64_mingw
            # --- ИЗМЕНЕНИЕ №1: Переключаемся на стабильную LTS-версию ---
            qt_version: '6.5.3'
          - os: ubuntu-latest
            qt_arch: gcc_64
            qt_version: '6.5.3'
          - os: macos-13
            qt_arch: clang_64
            qt_version: '6.5.3'

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt_version }}
        arch: ${{ matrix.qt_arch }}
        # --- ИЗМЕНЕНИЕ №2: Указываем правильные имена пакетов ---
        # 'widgets' не нужен (идет в комплекте), 'linguisttools' находится внутри 'qttools'
        modules: 'qttools multimedia'

    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libxcb-xinerama0 libxkbcommon-x11-0

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build Project
      run: cmake --build build --config Release --parallel
